Formatting cleanups and minor fixes.
thesandlord/SlackEngine pull request #3
Opened 2016-12-01 23:59 UTC by mbrukman

* Added missing code formatting where needed, e.g., to show `<` and `>`
* Capitalize uses of "Slack"
* Convert triple-backticks to single-backticks for inline code formatting
* Link directly to the license file
* Add a disclaimer section for visibility

2016-12-30 19:30 UTC, thesandlord commented
One nit, why are the links to the files in code quotes? Makes it look strange IMO.

For example:
Edit [`constants.php`](constants.php)

vs:
Edit [constants.php](constants.php)

Aside from that LGTM

2016-12-30 19:32 UTC, thesandlord requested changes

2016-12-30 19:32 UTC, thesandlord commented on README.md
> +* Edit [`constants.php`](constants.php)
Why are there backticks around constants.php

2016-12-30 19:32 UTC, thesandlord commented on README.md
> +* Edit [`app.yaml`](app.yaml)
Why are there backticks around app.yaml

2016-12-30 20:43 UTC, mbrukman commented on README.md
> +* Edit [`app.yaml`](app.yaml)
Removed.

2016-12-30 20:43 UTC, mbrukman commented on README.md
> +* Edit [`constants.php`](constants.php)
Removed.

2016-12-30 20:45 UTC, mbrukman commented
I used backticks on the filenames because filenames and paths get code-formatted similarly to shell commands and code samples, since they're used verbatim rather than serve as examples.

That said, I don't have a very strong feeling about it, so I've removed them in both cases.

2017-01-11 19:35 UTC, thesandlord approved these changes

2017-01-11 19:35 UTC, merged